---
- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest

    - name: Add index page
      template:
        src: index.html
        dest: /var/www/html/index.html

    - name: start nginx
      service:
        name: nginx
        state: started
